name: Bug 反馈
title: "[Bug]: "
description: 提交 Bug 反馈以帮助我们改进代码
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 确认项
      description: 请确认以下选项
      options:
        - label: 问题的标题明确
          required: true
        - label: 我翻阅过其他的 issue 并且找不到类似的问题
          required: true
        - label: 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个 Bug
          required: true
        - label: 我已经尝试过在最新的代码中修复这个问题
          required: false
  - type: dropdown
    id: env-os
    attributes:
      label: 操作系统
      description: 选择运行 NoneBot 的系统
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: env-python-ver
    attributes:
      label: Python 版本
      description: 填写运行 NoneBot 的 Python 版本
      placeholder: e.g. 3.11.0
    validations:
      required: true

  - type: input
    id: env-nb-ver
    attributes:
      label: NoneBot 版本
      description: 填写 NoneBot 版本
      placeholder: e.g. 2.0.0
    validations:
      required: true

  - type: input
    id: env-adapter
    attributes:
      label: 适配器
      description: 填写使用的Red适配器版本
      placeholder: e.g. 0.5.1
    validations:
      required: true

  - type: input
    id: env-protocol
    attributes:
      label: 协议端
      description: 填写 Chronocat 版本
      placeholder: e.g. 0.0.52
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: 描述问题
      description: 清晰简洁地说明问题是什么
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤
      description: 提供能复现此问题的详细操作步骤
      placeholder: |
        1. 首先……
        2. 然后……
        3. 发生……
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望的结果
      description: 清晰简洁地描述你期望发生的事情

  - type: textarea
    id: logs
    attributes:
      label: 截图或日志
      description: 提供有助于诊断问题的任何日志和截图

  - type: textarea
    id: config
    attributes:
      label: Nonebot 配置项
      description: Nonebot 配置项 (如果你的配置文件中包含敏感信息，请自行删除)
      render: dotenv
      placeholder: |
        # e.g.
        # KEY=VALUE
        # KEY2=VALUE2
